# App
spring.application.name=carmarket

# PostgreSQL - Supabase
spring.datasource.url=jdbc:postgresql://db.rzcmadlpnvnnunkxlmwn.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Car_market@27

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cloudinary
cloudinary.cloud-name=dqt4c5hjb
cloudinary.api-key=755941584775881
cloudinary.api-secret=zbN3FCKb_J4KKTdJXh4Eu22Z0DQ

# File upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=40MB

# Port
server.port=8080